package bmatch.tech.hello.dao;

import bmatch.tech.hello.dataobject.File;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    @Delete({
        "delete from file",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Sun Dec 09 22:49:54 GMT+08:00 2018
     */
    @Insert({
        "insert into file (id, name, ",
        "type, folderName, ",
        "gmtCreated, gmtModified)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=VARCHAR}, #{foldername,jdbcType=VARCHAR}, ",
        "now(), now())"
    })
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Sun Dec 09 22:49:54 GMT+08:00 2018
     */
    @Select({
        "select",
        "id, name, type, folderName, gmtCreated, gmtModified",
        "from file",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="folderName", property="foldername", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    File selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Sun Dec 09 22:49:54 GMT+08:00 2018
     */
    @Select({
        "select",
        "id, name, type, folderName, gmtCreated, gmtModified",
        "from file"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.VARCHAR),
        @Result(column="folderName", property="foldername", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmtCreated", property="gmtcreated", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmtModified", property="gmtmodified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<File> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Sun Dec 09 22:49:54 GMT+08:00 2018
     */
    @Update({
        "update file",
        "set name = #{name,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=VARCHAR},",
          "folderName = #{foldername,jdbcType=VARCHAR},",
          "gmtModified = now()",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(File record);
}