package bmatch.tech.hello.dataobject;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.name
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.type
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.folderName
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private String foldername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private Date gmtcreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    private Date gmtmodified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.name
     *
     * @return the value of file.name
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.name
     *
     * @param name the value for file.name
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.type
     *
     * @return the value of file.type
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.type
     *
     * @param type the value for file.type
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.folderName
     *
     * @return the value of file.folderName
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public String getFoldername() {
        return foldername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.folderName
     *
     * @param foldername the value for file.folderName
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setFoldername(String foldername) {
        this.foldername = foldername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.gmtCreated
     *
     * @return the value of file.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public Date getGmtcreated() {
        return gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.gmtCreated
     *
     * @param gmtcreated the value for file.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setGmtcreated(Date gmtcreated) {
        this.gmtcreated = gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.gmtModified
     *
     * @return the value of file.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public Date getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.gmtModified
     *
     * @param gmtmodified the value for file.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:49:53 GMT+08:00 2018
     */
    public void setGmtmodified(Date gmtmodified) {
        this.gmtmodified = gmtmodified;
    }
}