package bmatch.tech.hello.dataobject;

import java.util.Date;

public class Folder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.id
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.name
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    private Date gmtcreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    private Date gmtmodified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.id
     *
     * @return the value of folder.id
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.id
     *
     * @param id the value for folder.id
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.name
     *
     * @return the value of folder.name
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.name
     *
     * @param name the value for folder.name
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.gmtCreated
     *
     * @return the value of folder.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public Date getGmtcreated() {
        return gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.gmtCreated
     *
     * @param gmtcreated the value for folder.gmtCreated
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public void setGmtcreated(Date gmtcreated) {
        this.gmtcreated = gmtcreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.gmtModified
     *
     * @return the value of folder.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public Date getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.gmtModified
     *
     * @param gmtmodified the value for folder.gmtModified
     *
     * @mbg.generated Sun Dec 09 22:55:28 GMT+08:00 2018
     */
    public void setGmtmodified(Date gmtmodified) {
        this.gmtmodified = gmtmodified;
    }
}